name: value_stream_builder
description: Widget that can be used instead of StreamBuilder, to handle non-null data from ValueStream implementations, like for ex. BehaviorSubject.
version: 1.0.0
maintainer: Michał Dziwota (@dzziwny)
repository: https://github.com/dzziwny/value_stream_builder
homepage:

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  rxdart: ^0.27.5

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
